name: Install cosmocc
description: Install cosmocc on GitHub Actions
author: Brett Jia

inputs:
  version:
    description: Cosmopolitan release version
    required: true
    default: latest

runs:
  using: composite

  steps:
    - name: Download and extract
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [[ "${VERSION}" == "latest" ]]; then
          VERSION=$(curl -s -S https://api.github.com/repos/jart/cosmopolitan/releases | jq -r .[0].tag_name)
        fi

        INSTALL_DIR="${{ runner.temp }}/cosmocc-${VERSION}"
        INSTALL_DIR_FORMATTED=${INSTALL_DIR}
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          INSTALL_DIR_FORMATTED=$(cygpath -w ${INSTALL_DIR})
        fi
        echo "Using install dir ${INSTALL_DIR}"

        rm -rf ${INSTALL_DIR}
        mkdir -p ${INSTALL_DIR}
        cd ${INSTALL_DIR}

        echo "Downloading cosmocc ${VERSION}"
        curl -s -S -f -L -o cosmocc.zip https://github.com/jart/cosmopolitan/releases/download/${VERSION}/cosmocc-${VERSION}.zip

        if [[ "${{ runner.os }}" == "Windows" ]]; then
          7z.exe x cosmocc.zip
          echo ${INSTALL_DIR_FORMATTED}\\bin >> $GITHUB_PATH
        else
          unzip -qq cosmocc.zip
          echo ${INSTALL_DIR_FORMATTED}/bin >> $GITHUB_PATH
        fi

    - name: Verify cosmocc version
      shell: bash
      run: |
        cosmocc --version