name: Test action
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        version: ${{ inputs.version || 'latest' }}
